#!/usr/bin/env python2

from __future__ import print_function

import logging
import argparse
import time
import sys

import arista.platforms
from arista.core.platform import getPlatform, getSysEeprom, getPlatforms
import arista.core.utils as utils

def doSetup(args, platform):
   logging.debug('setting up platform')
   platform.setup()
   if args.reset:
      logging.debug('taking devices out of reset')
      platform.resetOut()

def doClean(args, platform):
   if args.reset:
      logging.debug('puting devices in reset')
      platform.resetIn()
   logging.debug('cleaning up platform')
   platform.clean()

def doReset(args, platform):
   if args.reset_out:
      platform.resetOut()
   elif args.reset_in:
      platform.resetIn()
   elif args.reset_toggle:
      platform.resetIn()
      time.sleep(args.reset_delay)
      platform.resetOut()
   else:
      logging.info('nothing to do')

def doPlatforms(args):
   print('supported platforms:')
   for platform in sorted(getPlatforms()):
      print(' -', platform)

def doSysEeprom(args):
   for key, value in getSysEeprom().items():
      print('%s: %s' % (key, value))

def todo(*args, **kwargs):
   raise NotImplementedError

def parseArgs():
   parser = argparse.ArgumentParser(
      description='Arista driver initialisation framework',
      formatter_class=argparse.ArgumentDefaultsHelpFormatter
   )
   parser.add_argument('-p', '--platform', type=str,
                       help='name of the platform to load')
   parser.add_argument('-l', '--logfile', type=str,
                       help='log file to log to')
   parser.add_argument('-v', '--verbose', action='store_true',
                       help='increase verbosity')
   parser.add_argument('-s', '--simulation', action='store_true',
                       help='force simulation mode')

   subparsers = parser.add_subparsers(dest='action')
   sub = subparsers.add_parser('help', help='print a help message')
   sub = subparsers.add_parser('platforms', help='show supported platforms')
   sub = subparsers.add_parser('syseeprom', help='show system eeprom content')

   sub = subparsers.add_parser('dump', help='dump information on this platform')
   sub = subparsers.add_parser('setup', help='setup drivers for this platform')
   sub.add_argument('-r', '--reset', action='store_true',
                    help='put devices out of reset after init')
   sub = subparsers.add_parser('clean', help='unload drivers for this platform')
   sub.add_argument('-r', '--reset', action='store_true',
                    help='put devices in reset before cleanup')
   sub = subparsers.add_parser('reset', help='put component in or out reset')
   sub.add_argument('device', nargs='*', # TODO: use this
                    help='device(s) to put in or out of reset')
   sub.add_argument('-t', '--toggle', action='store_true', dest='reset_toggle',
                    help='put components in and out of reset')
   sub.add_argument('-i', '--in', action='store_true', dest='reset_in',
                    help='put components in reset')
   sub.add_argument('-o', '--out', action='store_true', dest='reset_out',
                    help='put components out of reset')
   sub.add_argument('-d', '--delay', type=int, default=1, dest='reset_delay',
                    help='time to wait between in and out in seconds')

   args = parser.parse_args()
   if args.action == 'help':
      parser.print_help()
      sys.exit(0)
   return args

def main():
   args = parseArgs()

   if args.simulation:
      utils.simulation = True

   loglevel = logging.DEBUG if args.verbose else logging.INFO
   logging.basicConfig(format='%(levelname)s: %(message)s', level=loglevel,
                       filename=args.logfile)
   if utils.inSimulation():
      logging.info('Running in simulation mode')

   logging.debug(args)

   generic_commands = {
      'platforms': doPlatforms,
      'syseeprom': doSysEeprom,
   }

   platform_commands = {
      'dump':  lambda _, x: x.dump(),
      'setup': doSetup,
      'clean': doClean,
      'status': todo,
      'reset': doReset,
   }

   if args.action in generic_commands:
      generic_commands[args.action](args)
   elif args.action in platform_commands:
      platform_commands[args.action](args, getPlatform(args.platform))
   else:
      logging.error("Command %s doesn't exists" % args.command)

if __name__ == '__main__':
   main()

