EXTRA_CFLAGS += -Wall -Werror -I/usr/include/scd
KBUILD_EXTRA_SYMBOLS += /lib/modules/EosKernel/extra/scd-Module.symvers
obj-m += scd.o
obj-m += sonic-support-driver.o
obj-m += crow-fan-driver.o
obj-m += raven-fan-driver.o
